custom:
  - "https://www.paypal.com/cgi-bin/webscr?cmd=_xclick&business=ericstratigakis%40gmail.com&item_name=Shop%20tool%20support&amount=9.00&currency_code=CAD&no_shipping=1&button_subtype=services&return=https%3A%2F%2Fabstractigakis.com%2Fca%2Fthanks-9.html&rm=1"
  - "https://abstractigakis.com/ca/offer.html"
